pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                def mvnHome = tool name: 'Apache Maven 3.6.0', type: 'maven'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
